apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    name: alpine
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - "sleep"
    args:
      - "100000"
    volumeMounts:
      - mountPath: /etc/config
        name: config-vol
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: config-vol
      configMap:
        name: my-config
